export const ActionTypes = {
  SIGN_UP_USER: "SIGN_UP_USER",
  SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
  SIGN_UP_USER_FAIL: "SIGN_UP_USER_FAIL",
  SIGN_IN_USER: "SIGN_IN_USER",
  SIGN_IN_USER_SUCCESS: "SIGN_IN_USER_SUCCESS",
  SIGN_IN_USER_FAIL: "SIGN_IN_USER_FAIL",
  ADD_TOAST: "ADD_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",

  REQUEST_INSTITUTE: "REQUEST_INSTITUTE",
  REQUEST_INSTITUTE_SUCCESS: "REQUEST_INSTITUTE_SUCCESS",
  REQUEST_INSTITUTE_FAIL: "REQUEST_INSTITUTE_FAIL",

  GET_ROLES: "GET_ROLES",
  GET_ROLES_SUCCESS: "GET_ROLES_SUCCESS",
  GET_ROLES_FAIL: "GET_ROLES_FAIL",

  GET_STUDENT_TEACHER_CLASSES: "GET_STUDENT_TEACHER_CLASSES",
  GET_STUDENT_TEACHER_CLASSES_SUCCESS: "GET_STUDENT_TEACHER_CLASSES_SUCCESS",
  GET_STUDENT_TEACHER_CLASSES_FAIL: "GET_STUDENT_TEACHER_CLASSES_FAIL",

  GET_DEPARTMENT_CLASSES: "GET_DEPARTMENT_CLASSES",
  GET_DEPARTMENT_CLASSES_SUCCESS: "GET_DEPARTMENT_CLASSES_SUCCESS",
  GET_DEPARTMENT_CLASSES_FAIL: "GET_DEPARTMENT_CLASSES_FAIL",

  GET_INSTITUTE_CLASSES: "GET_INSTITUTE_CLASSES",
  GET_INSTITUTE_CLASSES_SUCCESS: "GET_INSTITUTE_CLASSES_SUCCESS",
  GET_INSTITUTE_CLASSES_FAIL: "GET_INSTITUTE_CLASSES_FAIL",
  CLEAR_CLASSES: "CLEAR_CLASSES",

  GET_PARTICIPANTS_CLASS: "GET_PARTICIPANTS_CLASS",
  GET_PARTICIPANTS_CLASS_SUCCESS: "GET_PARTICIPANTS_CLASS_SUCCESS",
  GET_PARTICIPANTS_CLASS_FAIL: "GET_PARTICIPANTS_CLASS_FAIL",
  CLEAR_PARTICIPANTS: "CLEAR_PARTICIPANTS",

  CREATE_INDEPENDENT_CLASS: "CREATE_INDEPENDENT_CLASS",
  CREATE_INDEPENDENT_CLASS_SUCCESS: "CREATE_INDEPENDENT_CLASS_SUCCESS",
  CREATE_INDEPENDENT_CLASS_FAIL: "CREATE_INDEPENDENT_CLASS_FAIL"

}
