export const ActionTypes = {
  SET_USER_ACTION: "SET_USER_ACTION",
  SET_USER_ACTION_SUCCESS: "SET_USER_ACTION_SUCCESS",
  SIGN_UP_USER: "SIGN_UP_USER",
  SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
  SIGN_UP_USER_FAIL: "SIGN_UP_USER_FAIL",
  SIGN_IN_USER: "SIGN_IN_USER",
  SIGN_IN_USER_SUCCESS: "SIGN_IN_USER_SUCCESS",
  SIGN_IN_USER_FAIL: "SIGN_IN_USER_FAIL",
  ADD_TOAST: "ADD_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",

  REQUEST_INSTITUTE: "REQUEST_INSTITUTE",
  REQUEST_INSTITUTE_SUCCESS: "REQUEST_INSTITUTE_SUCCESS",
  REQUEST_INSTITUTE_FAIL: "REQUEST_INSTITUTE_FAIL"
}
