export const ActionTypes = {
  SIGN_UP_USER: "SIGN_UP_USER",
  SIGN_UP_USER_SUCCESS: "SIGN_UP_USER_SUCCESS",
  SIGN_UP_USER_FAIL: "SIGN_UP_USER_FAIL",
  SIGN_IN_USER: "SIGN_IN_USER",
  SIGN_IN_USER_SUCCESS: "SIGN_IN_USER_SUCCESS",
  SIGN_IN_USER_FAIL: "SIGN_IN_USER_FAIL",
  ADD_TOAST: "ADD_TOAST",
  REMOVE_TOAST: "REMOVE_TOAST",

  // INSTITUTE ACTIONS
  REQUEST_INSTITUTE: "REQUEST_INSTITUTE",
  REQUEST_INSTITUTE_SUCCESS: "REQUEST_INSTITUTE_SUCCESS",
  REQUEST_INSTITUTE_FAIL: "REQUEST_INSTITUTE_FAIL",

  GET_INSTITUTE_REQUESTS: "GET_INSTITUTE_REQUESTS",
  GET_INSTITUTE_REQUESTS_SUCCESS: "GET_INSTITUTE_REQUESTS_SUCCESS",
  GET_INSTITUTE_REQUESTS_FAIL: "GET_INSTITUTE_REQUESTS_FAIL",

  GET_INSTITUTES: "GET_INSTITUTES",
  GET_INSTITUTES_SUCCESS: "GET_INSTITUTES_SUCCESS",
  GET_INSTITUTES_FAIL: "GET_INSTITUTES_FAIL",

  ACCEPT_REJECT_INSTITUTE: "ACCEPT_REJECT_INSTITUTE",
  ACCEPT_REJECT_INSTITUTE_SUCCESS: "ACCEPT_REJECT_INSTITUTE_SUCCESS",
  ACCEPT_REJECT_INSTITUTE_FAIL: "ACCEPT_REJECT_INSTITUTE_FAIL",

  DELETE_INSTITUTE: "DELETE_INSTITUTE",
  DELETE_INSTITUTE_SUCCESS: "DELETE_INSTITUTE_SUCCESS",
  DELETE_INSTITUTE_FAIL: "DELETE_INSTITUTE_FAIL",

  RESTORE_INSTITUTE: "RESTORE_INSTITUTE",
  RESTORE_INSTITUTE_SUCCESS: "RESTORE_INSTITUTE_SUCCESS",
  RESTORE_INSTITUTE_FAIL: "RESTORE_INSTITUTE_FAIL",

  ADD_INSTITUTE_ADMIN: "ADD_INSTITUTE_ADMIN",
  ADD_INSTITUTE_ADMIN_SUCCESS: "ADD_INSTITUTE_ADMIN_SUCCESS",
  ADD_INSTITUTE_ADMIN_FAIL: "ADD_INSTITUTE_ADMIN_FAIL",

  GET_DEPARTMENTS_IN_INSTITUTE: "GET_DEPARTMENTS_IN_INSTITUTE",
  GET_DEPARTMENTS_IN_INSTITUTE_SUCCESS: "GET_DEPARTMENTS_IN_INSTITUTE_SUCCESS",
  GET_DEPARTMENTS_IN_INSTITUTE_FAIL: "GET_DEPARTMENTS_IN_INSTITUTE_FAIL",

  ADD_DEPARTMENT_IN_INSTITUTE: "ADD_DEPARTMENT_IN_INSTITUTE",
  ADD_DEPARTMENT_IN_INSTITUTE_SUCCESS: "ADD_DEPARTMENT_IN_INSTITUTE_SUCCESS",
  ADD_DEPARTMENT_IN_INSTITUTE_FAIL: "ADD_DEPARTMENT_IN_INSTITUTE_FAIL",
  //END INSTITUTE ACTIONS

  GET_ROLES: "GET_ROLES",
  GET_ROLES_SUCCESS: "GET_ROLES_SUCCESS",
  GET_ROLES_FAIL: "GET_ROLES_FAIL",

  GET_STUDENT_TEACHER_CLASSES: "GET_STUDENT_TEACHER_CLASSES",
  GET_STUDENT_TEACHER_CLASSES_SUCCESS: "GET_STUDENT_TEACHER_CLASSES_SUCCESS",
  GET_STUDENT_TEACHER_CLASSES_FAIL: "GET_STUDENT_TEACHER_CLASSES_FAIL",

  GET_DEPARTMENT_CLASSES: "GET_DEPARTMENT_CLASSES",
  GET_DEPARTMENT_CLASSES_SUCCESS: "GET_DEPARTMENT_CLASSES_SUCCESS",
  GET_DEPARTMENT_CLASSES_FAIL: "GET_DEPARTMENT_CLASSES_FAIL",

  GET_INSTITUTE_CLASSES: "GET_INSTITUTE_CLASSES",
  GET_INSTITUTE_CLASSES_SUCCESS: "GET_INSTITUTE_CLASSES_SUCCESS",
  GET_INSTITUTE_CLASSES_FAIL: "GET_INSTITUTE_CLASSES_FAIL",
  CLEAR_CLASSES: "CLEAR_CLASSES",

  // Participants handler
  GET_PARTICIPANTS_CLASS: "GET_PARTICIPANTS_CLASS",
  GET_PARTICIPANTS_CLASS_SUCCESS: "GET_PARTICIPANTS_CLASS_SUCCESS",
  GET_PARTICIPANTS_CLASS_FAIL: "GET_PARTICIPANTS_CLASS_FAIL",
  CLEAR_PARTICIPANTS: "CLEAR_PARTICIPANTS",

  REMOVE_PARTICIPANT: "REMOVE_PARTICIPANT",
  REMOVE_PARTICIPANT_SUCCESS: "REMOVE_PARTICIPANT_SUCCESS",
  REMOVE_PARTICIPANT_FAIL: "REMOVE_PARTICIPANT_FAIL",

  CREATE_INDEPENDENT_CLASS: "CREATE_INDEPENDENT_CLASS",
  CREATE_INDEPENDENT_CLASS_SUCCESS: "CREATE_INDEPENDENT_CLASS_SUCCESS",
  CREATE_INDEPENDENT_CLASS_FAIL: "CREATE_INDEPENDENT_CLASS_FAIL",

  ADD_PARTICIPANTS_IN_CLASS: "ADD_PARTICIPANTS_IN_CLASS",
  ADD_PARTICIPANTS_IN_CLASS_SUCCESS: "ADD_PARTICIPANTS_IN_CLASS_SUCCESS",
  ADD_PARTICIPANTS_IN_CLASS_FAIL: "ADD_PARTICIPANTS_IN_CLASS_FAIL"
}
